### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by aloncarmel111** [cyberark/conjur-base-image#16]
## Is your feature request related to a problem? Please describe.

Ruby installation size is  170MB , most of the size is because of documentation and static library
/var/lib/ruby/lib/libruby-static.a is 60 MB 
/var/lib/ruby/share/ri is 59MB

## Describe the solution you would like

After this change the ruby installation size is 41MB

To install Ruby without documentation and static library

```
./configure --with-openssl-dir=/usr/local/ssl  --disable-install-doc --disable-install-rdoc --disable-install-static-library  --disable-install-capi  --prefix=/var/lib/ruby
make -j4
make install
```

` --disable-install-doc` -  do not install either rdoc indexes or C API
                          documents during install
  `--disable-install-rdoc` - do not install rdoc indexes during install
` --disable-install-capi` - do not install C API documents during install
  `--disable-install-static-library`  -  do not install static ruby library

**Comment by micahlee** [comment]
@aloncarmel111, this looks like a nice reduction in image size!

Question regarding:
```
--disable-install-static-library  --disable-install-capi
```
How did you determine these are not used in any of our subcomponents?

**Comment by aloncarmel111** [comment]
@micahlee , Before applying those change, all subcomponents needs to be validated.
`--disable-install-capi`-  disables building and installing C API **documents**
maybe we should set the `--enable-shared` option this will disable static ruby library installation(see https://bugs.ruby-lang.org/issues/12845) , also this is the default option when installing Ruby using `apt-get` command
