### ISSUE TITLE
PG version hardcoded, causing build to fail each lastest update

### ISSUE THREAD

**Issue by uCatu** [cyberark/conjur-base-image#21]
We are using lastet and hardcoded version
for example latest was `12-12.2` and we had local hardcoded:
`PG_VERSION=12-12.2`

When ubuntu update, build failed, and we were forced to update the hardcoded version to:
`PG_VERSION=12-12.4`

Solution can be, to not use version at all, just save file name as we want "pg_client" or something, or to run find/ls to get the filename automatically

see [PR](https://github.com/cyberark/conjur-base-image/pull/20) for ref

**Comment by tarnowsc** [comment]
Fixed with #112
